spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create
    show_sql: true
    format_sql: true
    use_sql_comments: true
    openInView: false